import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const root = new URL('../', import.meta.url);

export async function renderClientBundle() {
  const polling = await readFile(new URL('src/polling.mjs', root), 'utf8');
  const client = await readFile(new URL('src/client.mjs', root), 'utf8');
  const body = (polling + '\n' + client.replace(/^import .*polling\.mjs.*\r?\n/, ''))
    .replace(/^export /gm, '');
  const indented = body.split('\n').map(line => '    ' + line).join('\n');
  return [
    '/* Generated by scripts/build.mjs; edit src/client.mjs and src/polling.mjs. */',
    'window.__ModuleLoader__.load({',
    "  id: 'dsh-show-git-brunch',",
    '  factory: (require) => {',
    "    const React = require('react');",
    indented,
    '    return createClientPlugin(React);',
    '  },',
    '});',
    '',
  ].join('\n');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  await mkdir(new URL('lib/', root), { recursive: true });
  await writeFile(new URL('lib/client.js', root), await renderClientBundle(), 'utf8');
}
