/* Generated by scripts/build.mjs; edit src/client.mjs and src/polling.mjs. */
window.__ModuleLoader__.load({
  id: 'dsh-show-git-brunch',
  factory: (require) => {
    const React = require('react');
    const POLL_MS = 5000;
    const REQUEST_TIMEOUT_MS = 4000;
    
    /** Own visible-page refresh events and ensure only one branch request is active. */
    function createBranchPolling({
      request,
      onValue,
      document: doc = globalThis.document,
      window: win = globalThis.window,
      setInterval: startInterval = globalThis.setInterval,
      clearInterval: stopInterval = globalThis.clearInterval,
      setTimeout: startTimeout = globalThis.setTimeout,
      clearTimeout: stopTimeout = globalThis.clearTimeout,
    }) {
      let disposed = false;
      let interval;
      let active;
      let generation = 0;
    
      const clearActive = () => {
        generation++;
        if (active) {
          active.controller.abort();
          stopTimeout(active.timeout);
          active = undefined;
        }
      };
      const refresh = () => {
        if (disposed || doc.visibilityState === 'hidden' || active) return;
        const token = ++generation;
        const controller = new AbortController();
        const timeout = startTimeout(() => {
          controller.abort();
          if (!disposed && active?.token === token) {
            active = undefined;
            onValue(null);
          }
        }, REQUEST_TIMEOUT_MS);
        active = { token, controller, timeout };
        let pending;
        try {
          pending = request(controller.signal);
        } catch {
          pending = Promise.reject(new Error('branch request failed'));
        }
        Promise.resolve(pending)
          .then(value => {
            if (!disposed && active?.token === token && !controller.signal.aborted) onValue(value);
          })
          .catch(() => {
            if (!disposed && active?.token === token && !controller.signal.aborted) onValue(null);
          })
          .finally(() => {
            if (active?.token === token) {
              stopTimeout(timeout);
              active = undefined;
            }
          });
      };
      const start = () => {
        if (disposed || doc.visibilityState === 'hidden' || interval !== undefined) return;
        refresh();
        interval = startInterval(refresh, POLL_MS);
      };
      const stop = () => {
        if (interval !== undefined) stopInterval(interval);
        interval = undefined;
        clearActive();
      };
      const visibility = () => {
        if (doc.visibilityState === 'hidden') {
          stop();
          if (!disposed) onValue(null);
        } else {
          start();
        }
      };
      const focus = () => refresh();
    
      doc.addEventListener('visibilitychange', visibility);
      win.addEventListener('focus', focus);
      start();
    
      return () => {
        if (disposed) return;
        disposed = true;
        stop();
        doc.removeEventListener('visibilitychange', visibility);
        win.removeEventListener('focus', focus);
      };
    }
    
    
    const labelStyle = { display:'inline-flex', alignItems:'center', gap:'4px', minWidth:0, maxWidth:'240px', color:'var(--text-tertiary, #6b7280)', fontSize:'12px', lineHeight:1, whiteSpace:'nowrap' };
    const textStyle = { overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap' };
    
    function validBranch(value) {
      if (value === null || typeof value !== 'object' || !['branch','detached'].includes(value.kind)
        || typeof value.name !== 'string' || value.name.length === 0 || value.name.length > 4096) return null;
      return { kind: value.kind, name: value.name };
    }
    
    function displayBranch(value) {
      return value.kind === 'detached' ? 'detached ' + value.name : value.name;
    }
    
    function truncate(value, limit = 48) {
      const chars = Array.from(value);
      return chars.length <= limit ? value : chars.slice(0, limit - 1).join('') + '…';
    }
    
    function BranchIcon(React) {
      return React.createElement('svg', {width:14,height:14,viewBox:'0 0 16 16',fill:'none','aria-hidden':true,style:{flex:'0 0 auto'}},
        React.createElement('circle',{cx:5,cy:3,r:1.5,stroke:'currentColor',strokeWidth:1.25}),
        React.createElement('circle',{cx:5,cy:13,r:1.5,stroke:'currentColor',strokeWidth:1.25}),
        React.createElement('circle',{cx:11,cy:5,r:1.5,stroke:'currentColor',strokeWidth:1.25}),
        React.createElement('path',{d:'M5 4.5v7M6.5 10c3 0 4.5-1.5 4.5-3.5',stroke:'currentColor',strokeWidth:1.25,strokeLinecap:'round'}));
    }
    
    function createClientPlugin(React) {
      function BranchLabel({ sessionId, useSessions }) {
        const cwd = useSessions(state => state.byId[sessionId]?.cwd);
        const identity = String(sessionId) + '\0' + (cwd ?? '');
        const [state, setState] = React.useState({ identity:'', value:null });
    
        React.useEffect(() => {
          setState({ identity, value:null });
          if (typeof cwd !== 'string' || cwd.length === 0) return undefined;
          return createBranchPolling({
            request: async signal => {
              const result = await this.connection.rpc.call('/show-git-brunch', 'branch', { sessionId }, signal);
              return result?.ok === true ? validBranch(result.value) : null;
            },
            onValue: value => setState({ identity, value: validBranch(value) }),
          });
        }, [identity, sessionId, cwd]);
    
        const value = state.identity === identity ? state.value : null;
        if (value === null) return null;
        const full = displayBranch(value);
        return React.createElement('span', {style:labelStyle,title:full,'aria-label':'Git branch: ' + full},
          BranchIcon(React), React.createElement('span',{style:textStyle},truncate(full)));
      }
    
      let connection;
      function BoundLabel(props) { return BranchLabel.call({connection}, props); }
      return {
        inject: ['slots','connection'],
        apply(ctx) {
          connection = ctx.connection;
          ctx.slots.inject('conversation.session.header.actions', () => ctx.slots.register({
            name:'conversation.session.header.actions', id:'show-git-brunch', order:-9, label:'Git branch',
          }, BoundLabel));
        },
      };
    }
    
    return createClientPlugin(React);
  },
});
